---
kind: pipeline
type: kubernetes
name: Discover Velocity releases
trigger:
  event:
    exclude:
      - promote
steps:
  - name: Build
    image: golang:1.18.2-alpine
    commands:
      - go build -o bin/discover github.com/dockcenter/velocity/cmd/discover
  - name: Discover releases
    image: alpine
    when:
      event:
        - cron
    environment:
      DRONE_SERVER: http://drone
      DRONE_TOKEN:
        from_secret: drone_token
    commands:
      - apk --no-cache add curl tar
      - curl -L https://github.com/harness/drone-cli/releases/latest/download/drone_linux_amd64.tar.gz | tar zx
      - install -t /usr/local/bin drone
      - bin/discover
      - sh scripts/promote.sh
  - name: Discover releases (dry run)
    image: alpine
    when:
      event:
        exclude:
          - cron
    environment:
      DRONE_SERVER: http://drone
      DRONE_TOKEN:
        from_secret: drone_token
      DRY_RUN: true
    commands:
      - apk --no-cache add curl tar
      - curl -L https://github.com/harness/drone-cli/releases/latest/download/drone_linux_amd64.tar.gz | tar zx
      - install -t /usr/local/bin drone
      - bin/discover
      - sh scripts/promote.sh

---
kind: pipeline
type: kubernetes
name: Publish
trigger:
  event:
    - promote
steps:
  - name: Download velocity
    image: busybox:stable
    commands:
      - wget -P velocity/ $DOWNLOAD_URL
  - name: Build Docker image
    image: plugins/docker
    when:
      target:
        - development
    settings:
      dockerfile: Dockerfile
      dry_run: true
      repo: dockcenter/velocity
      tags: ${DOCKER_TAGS}
      build_args_from_env:
        - DOWNLOAD_URL
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      mtu: 1440
  - name: Publish Docker image
    image: plugins/docker
    when:
      target:
        exclude:
          - development
    settings:
      dockerfile: Dockerfile
      repo: dockcenter/velocity
      tags: ${DOCKER_TAGS}
      build_args_from_env:
        - DOWNLOAD_URL
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      mtu: 1440

---
kind: signature
hmac: 563402d487604b8dfe12054d4e99f81d8eca588fe6ab79513aed1e45a0b710c9

...
