on:
  workflow_dispatch:
    inputs:
      downloadURL:
        description: Velocity download URL
        required: true
        type: string
      tags:
        description: docker/metadata-action tags definition
        required: true
        type: string

name: Build and push Docker image

jobs:
  docker-image:
    runs-on: ubuntu-latest
    name: Build and push Docker image

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Download velocity jar
        run: wget -P velocity/ ${{ inputs.downloadURL }}
      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: dockcenter/velocity
          tags: ${{ inputs.tags }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
      - name: Summary
        run: |
          echo "## Image tags" >> $GITHUB_STEP_SUMMARY
          while IFS= read -r line ;
            do echo "- $line" >> $GITHUB_STEP_SUMMARY;
          done <<< "$tags"
        env:
          tags: ${{ steps.docker_meta.outputs.tags }}